harnessApiVersion: '1.0'
type: SHELL_SCRIPT
outputVars: targetGroupArnCurrent
scriptString: |2

  echo "${context.p_les.targetGroupCurrent}"
scriptType: BASH
timeoutMillis: 600000
variables:
- name: targetGroupArnCurrent
  value: ${workflow.variables.targetGroupCurrentArn}
