harnessApiVersion: '1.0'
type: SHELL_SCRIPT
scriptString: "if [[ -z ${targetGroupArnCurrent} || ${targetGroupArnCurrent} == \"\
  null\" ]]\n    then \n        echo \"targetGroupArnCurrent is not set in the workflow\
  \ variables\"\n fi"
scriptType: BASH
timeoutMillis: 600000
variables:
- name: targetGroupArnCurrent
  value: ${workflow.variables.targetGroupCurrentArn}
